Update IREE to the tag iree-3.0.0
RechieKho/iree.gd pull request #106
Opened 2024-12-27 01:53 UTC by fire

Update to the latest IREE stable.

2024-12-27 03:15 UTC, RechieKho commented
<img width="902" alt="Screenshot 2024-12-27 at 11 14 12 AM" src="https://github.com/user-attachments/assets/22f9aba6-dcfe-44fb-b715-2d5fcfc75716" />

<img width="783" alt="Screenshot 2024-12-27 at 11 14 27 AM" src="https://github.com/user-attachments/assets/e3d625f6-8709-4e0e-a518-c8dd359df282" />

The samples broke. It outputs all 0s. Perhaps it is time to update the `.vmfb` byte codes as well.

2024-12-27 03:16 UTC, RechieKho requested changes
Got to update the byte code since it has some breaking change.

2024-12-27 05:20 UTC, fire commented
Ok, if I only keep?

* esrgan
* singlepose_thunder

2025-01-02 18:41 UTC, fire commented
@RechieKho had some trouble updating the bytecode.

Do you have any logs?

2025-01-03 10:57 UTC, RechieKho commented
https://github.com/iree-org/iree/issues/19568

I can't even compile them now :(

2025-01-18 00:47 UTC, fire commented
@RechieKho Try 3.1.0. No idea if it'll make a difference.

2025-01-18 03:04 UTC, fire commented
I've noticed a conversion failure on MacOS.

https://github.com/iree-gd/iree-gd-quickstart/actions/runs/12840284960/job/35808735132

2025-01-18 04:26 UTC, fire commented
I can confirm that old runtimes work with newer toolchain files, but newer toolchain files don't work with newer runtimes.

I probably want further confirmation.

2025-01-18 15:41 UTC, fire commented
On failure, the data is empty.

2025-11-10 19:55 UTC, fire commented
Closing I have no idea when this will work.

2025-11-10 19:55 UTC, closed without merging